server:
  port: '8080'



---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/blogging_app
    password: kethan
  application:
    name: demo
  devtools:
    restart:
      quiet-period: 500ms
      poll-interval: 1s
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to the Prod home page!!
management:
  endpoints:
    web:
      exposure:
        include: "*"
jwt:
  secret: 8978604d8a0016b19e43b7af3d88c440245768e5a8c6728c36958935ea87e73b4715d1a0906baba3275123bf645a93756cb2d14addb789c34cbce9563ffa31fafe0f0c240c177bef4de74e64006d0ff8c7a875bdb5c97fcda984a02816422ce7f79403d4ee92a6cdb5db8673840cd79df6fe5e70ff843c833f96baa5e1a52de3

